In [61]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import re

In [62]:
lists_path = "./dataset/raw_imdb_list.csv"
reviews_path = "./dataset/raw_imdb_reviews.csv"

lists_df = pd.read_csv(lists_path)
reviews_df = pd.read_csv(reviews_path)

In [63]:
lists_df = pd.read_csv(lists_path)
lists_df.head()

,Unnamed: 0,id,title,rating,genre,year
0,0,tt0369610,Jurassic World,6.9,"Action, Adventure, Sci-Fi",2015
1,1,tt3774694,Love,6.1,"Drama, Romance",2015
2,2,tt2361509,The Intern,7.1,"Comedy, Drama",2015
3,3,tt2381249,Mission: Impossible - Rogue Nation,7.4,"Action, Adventure, Thriller",2015
4,4,tt3460252,The Hateful Eight,7.8,"Crime, Drama, Mystery",2015

In [64]:
lists_df.columns

Index(['Unnamed: 0', 'id', 'title', 'rating', 'genre', 'year'], dtype='object')

In [65]:
lists_df.drop('Unnamed: 0', axis=1, inplace=True)

In [66]:
lists_df.shape

(250, 5)

In [67]:
lists_df.head()

,id,title,rating,genre,year
0,tt0369610,Jurassic World,6.9,"Action, Adventure, Sci-Fi",2015
1,tt3774694,Love,6.1,"Drama, Romance",2015
2,tt2361509,The Intern,7.1,"Comedy, Drama",2015
3,tt2381249,Mission: Impossible - Rogue Nation,7.4,"Action, Adventure, Thriller",2015
4,tt3460252,The Hateful Eight,7.8,"Crime, Drama, Mystery",2015

In [68]:
lists_df.dtypes

id         object
title      object
rating    float64
genre      object
year        int64
dtype: object

In [69]:
lists_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      250 non-null    object
 1   title   250 non-null    object
 2   rating  250 non-null    float64
 3   genre   250 non-null    object
 4   year    250 non-null    int64
dtypes: float64(1), int64(1), object(3)
memory usage: 9.9+ KB

In [70]:
lists_df.describe()

           rating         year
count  250.000000   250.000000
mean     7.280400  2019.500000
std      0.624191     2.878043
min      6.000000  2015.000000
25%      6.800000  2017.000000
50%      7.300000  2019.500000
75%      7.800000  2022.000000
max      8.700000  2024.000000

In [71]:
lists_df.isna().sum()

id        0
title     0
rating    0
genre     0
year      0
dtype: int64

In [72]:
lists_df.duplicated().sum()

np.int64(0)

In [73]:
lists = pd.read_csv("./dataset/raw_imdb_list.csv")
if "Unnamed: 0" in lists.columns:
    lists.drop("Unnamed: 0", axis=1, inplace=True)
lists_cleaned = lists.copy()
lists_cleaned.head()
lists_cleaned.to_csv("lists_cleaned.csv", index=False)

In [74]:
reviews_df = pd.read_csv(reviews_path, encoding="latin1")

In [75]:
reviews_df["review_rating"] = pd.to_numeric(reviews_df["review_rating"], errors="coerce")
reviews_df["imdb_id"] = reviews_df["imdb_id"].astype(str)

In [76]:
reviews_df.rename(columns={
    "imdb_id": "id",
    "review title": "review_title",
    "review": "review_text"
}, inplace=True)

In [77]:
reviews_df.columns

Index(['id', 'review_title', 'review_rating', 'review_text'], dtype='object')

In [78]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

reviews_df["clean_review"] = reviews_df["review_text"].apply(clean_text)

In [79]:
reviews_df.duplicated().sum()

np.int64(25)

In [80]:
reviews_df.drop_duplicates(inplace=True)

In [81]:
reviews_df.duplicated().sum()

np.int64(0)

In [82]:
reviews_df.dtypes

id                object
review_title      object
review_rating    float64
review_text       object
clean_review      object
dtype: object

In [83]:
reviews_df.isna().sum()

id                 0
review_title       0
review_rating    354
review_text        0
clean_review       0
dtype: int64

In [84]:
reviews_df['review_rating'] = reviews_df['review_rating'].fillna(0)

In [85]:
reviews_df.shape

(6216, 5)

In [86]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6216 entries, 0 to 6240
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             6216 non-null   object
 1   review_title   6216 non-null   object
 2   review_rating  6216 non-null   float64
 3   review_text    6216 non-null   object
 4   clean_review   6216 non-null   object
dtypes: float64(1), object(4)
memory usage: 291.4+ KB

In [87]:
reviews_df.describe()

       review_rating
count    6216.000000
mean        6.882400
std         2.534176
min         0.000000
25%         6.000000
50%         7.000000
75%         9.000000
max        10.000000

In [88]:
reviews_df.head()

,id,review_title,review_rating,review_text,clean_review
0,tt0369610,"Spielberg Magic, This Is Not. Still, a Visit t...",7.0,You may have heard some critics champion Juras...,you may have heard some critics champion juras...
1,tt0369610,"Not a patch on the original Jurassic Park, and...",7.0,The original Jurassic Park still is a personal...,the original jurassic park still is a personal...
2,tt0369610,Its a Jurassic World after all.,7.0,The 4th film in the Jurassic Park series and t...,the th film in the jurassic park series and th...
3,tt0369610,Worthy Sequel To One Of The Greatest Films Eve...,0.0,Let's start this by stating how much of a die ...,lets start this by stating how much of a die h...
4,tt0369610,Manages to somewhat return the Jurassic Park s...,6.0,Modernized and polished entry to the Jurassic ...,modernized and polished entry to the jurassic ...

In [89]:
reviews_df.to_csv("reviews_cleaned.csv", index=False)